### ISSUE TITLE
Installation problem with sonarqube 6.7

### ISSUE THREAD

**Issue by fpruvost** [lequal/sonar-icode-cnes-plugin#62]
When trying to install the plugin with my installation of sonarqube 6.7.7 I get the following error
```
2020.04.02 15:38:38 ERROR web[][o.s.s.p.Platform] Background initialization failed. Stopping SonarQube
java.lang.IllegalStateException: Fail to load plugin Sonar i-Code CNES plugin [icode]
        at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:88)
        at org.sonar.server.platform.platformlevel.PlatformLevel4.start(PlatformLevel4.java:581)
        at org.sonar.server.platform.Platform.start(Platform.java:211)
        at org.sonar.server.platform.Platform.startLevel34Containers(Platform.java:185)
        at org.sonar.server.platform.Platform.access$500(Platform.java:46)
        at org.sonar.server.platform.Platform$1.lambda$doRun$0(Platform.java:119)
        at org.sonar.server.platform.Platform$AutoStarterRunnable.runIfNotAborted(Platform.java:371)
        at org.sonar.server.platform.Platform$1.doRun(Platform.java:119)
        at org.sonar.server.platform.Platform$AutoStarterRunnable.run(Platform.java:355)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalStateException: Unable to register extension fr.cnes.sonar.plugins.icode.languages.ICodeQualityProfiles from plugin 'icode'
```
I've try with the releases 1.1.0, 1.0.2, 1.0.0.

**User environment:**
 - OS: CentOS Linux release 7.7.1908
 - Java version: openjdk version "11.0.6" 2020-01-14 LTS
 - i-Code version: 
 - Plugin version: 1.0.0, 1.0.2, 1.1.0

```
/opt/sonarqube/extensions/plugins# ll -tr
total 151648
-rw-r--r-- 1 sonarqube nobody   300101 Jul 20  2018 sonar-icode-cnes-plugin-1.0.0.jar
```

**Comment by begarco** [comment]
Hi @fpruvost,

Your configuration is not correct. SonarQube 6.7 should not be used with Java 11.

Please downgrade your Java version to Java 8 and it should run.

Benoît

**Comment by fpruvost** [comment]
Hi @begarco 

oh nice catch ! I was trying to install a sonarqube version 7.9 at the same time that's why I have upgraded java :)
The installation is just fine with java 8 and plugin version 1.3.0, thanks.
